export const goldenUnits = [
  {
    id: 1,
    name: "Siphonarioi",
    src: "/golden-units/barc-narf-gua-thumb.png",
    leadership: 300,
    masteryPoints: false,
    value: 10,
    era: "golden",
    icon: "/golden-icons/Siphonarioi.webp",
    type: ["ranged", "special"],
    description: "description",
    season: { number: 7, name: "Season of fire" },
    tree: {
      img: "https://conqhub.com/images/units/siphonarioi/barc-narf-gua-vet-expan.png",
      structure: [
        {
          name: "first",
          description: "description",
          img: "/unit.jpg",
          prev: null,
          id: 1,
          value: 1,
        },

        {
          name: "second",
          description: "description",
          img: "/unit.jpg",
          prev: 1,
          id: 2,
          value: 3,
        },
        {
          name: "third",
          description: "description",
          img: "/unit.jpg",
          prev: 2,
          id: 3,
          value: 3,
        },
        {
          name: "fourth",
          description: "description",
          img: "/unit.jpg",
          prev: 3,
          id: 4,
          value: 1,
        },
        {
          name: "fifth",
          description: "description",
          img: "/unit.jpg",
          prev: 4,
          id: 5,
          value: 3,
        },
        {
          name: "sixth",
          description: "description",
          img: "/unit.jpg",
          prev: 5,
          id: 6,
          value: 3,
        },
        {
          name: "seventh",
          description: "description",
          img: "/unit.jpg",
          prev: 6,
          id: 7,
          value: 3,
        },
        {
          name: "eighth",
          description: "description",
          img: "/unit.jpg",
          prev: 7,
          id: 8,
          value: 1,
        },
        {
          name: "ninth",
          description: "description",
          img: "/unit.jpg",
          prev: 8,
          id: 9,
          value: 3,
        },
        {
          name: "tenth",
          description: "description",
          img: "/unit.jpg",
          prev: 9,
          id: 10,
          value: 1,
        },
        {
          name: "eleventh",
          description: "description",
          img: "/unit.jpg",
          prev: 1,
          id: 11,
          value: 1,
        },
        {
          name: "twelfth",
          description: "description",
          img: "/unit.jpg",
          prev: 11,
          id: 12,
          value: 3,
        },
        {
          name: "thirteenth",
          description: "description",
          img: "/unit.jpg",
          prev: 12,
          id: 13,
          value: 3,
        },
        {
          name: "fourteenth",
          description: "description",
          img: "/unit.jpg",
          prev: 13,
          id: 14,
          value: 2,
        },
        {
          name: "fifteenth",
          description: "description",
          img: "/unit.jpg",
          prev: 14,
          id: 15,
          value: 3,
        },
        {
          name: "sixteenth",
          description: "description",
          img: "/unit.jpg",
          prev: 15,
          id: 16,
          value: 1,
        },
        {
          name: "seventeenth",
          description: "description",
          img: "/unit.jpg",
          prev: 16,
          id: 17,
          value: 2,
        },
        {
          name: "eighteenth",
          description: "description",
          img: "/unit.jpg",
          prev: 17,
          id: 18,
          value: 2,
        },
        {
          name: "nineteenth",
          description: "description",
          img: "/unit.jpg",
          prev: 18,
          id: 19,
          value: 3,
        },
        {
          name: "twentieth",
          description: "description",
          img: "/unit.jpg",
          prev: 19,
          id: 20,
          value: 1,
        },
      ],
    },
    formation: [
      {
        name: "Line",
        img: "https://conqhub.com/images/formations/line-single-horizontal.png",
        description: "description",
      },
      {
        name: "Cross Formation",
        img: "https://conqhub.com/images/formations/cross-formation.png",
        description: "description",
      },
    ],
    skills: [
      {
        name: "Firestorm",
        description:
          "The unit sprays a longer blast of hellfire that will set the enemy on fire for some time.",
        image: "https://conqhub.com/images/orders/firestorm.png",
      },
      {
        name: "Scorched Earth",
        description:
          "The unit sprays a quick burst of hellfire. Hellfire will continue to burn on the ground for an extended period of time, inflicting lots of burning damage to enemies passing through.",
        image: "https://conqhub.com/images/orders/scorched-earth.png",
      },
    ],
    dedicatedDoctrins: [
      {
        name: "Siphonarioi Hellfire Doctrine",
        img: "https://conqhub.com/images/doctrines/epic/siphonarioi-doctrine-ii.png",
        description: "description",
      },
      {
        name: "Siphonarioi Flamethrower Doctrine",
        img: "https://conqhub.com/images/doctrines/rare/siphonarioi-doctrine-i.png",
        description: "description",
      },
    ],
    kits: {
      name: "Siphonarioi Kit",
      img: "https://conqhub.com/images/supply-dump/kits/sipho_kit.png",
    },
  },
  {
    id: 2,
    name: "Cataphract Lancers",
    src: "/golden-units/cata_lan_pre.png",
    leadership: 305,
    masteryPoints: false,
    value: 5,
    era: "golden",
    icon: "/golden-icons/Elite_Cataphract_Lancers.webp",
  },
  {
    id: 3,
    name: "Chevaliers",
    src: "/golden-units/chevaliers_thumb.png",
    leadership: 340,
    masteryPoints: false,
    value: 6,
    era: "golden",
    icon: "/golden-icons/Company_Dordonnance.webp",
  },
  {
    id: 4,
    name: "Falconetti Gunners",
    src: "/golden-units/falco_gun.png",
    leadership: 300,
    masteryPoints: false,
    value: 10,
    era: "golden",
    icon: "/golden-icons/Falconetti_Gunners.webp",
  },
  {
    id: 5,
    name: "Fire Lancers",
    src: "/golden-units/fire_lan_pre.png",
    leadership: 285,
    masteryPoints: false,
    value: 4,
    era: "golden",
    icon: "/golden-icons/Fire_Lancers.webp",
  },
  {
    id: 6,
    name: "Hashashins",
    src: "/golden-units/hashashins_thumb.png",
    leadership: 295,
    masteryPoints: false,
    value: 2,
    era: "golden",
    icon: "/golden-icons/Hashashins.webp",
  },
  {
    id: 7,
    name: "Houndsmen",
    src: "/golden-units/houndsmen_thumb.png",
    leadership: 310,
    masteryPoints: false,
    value: 3,
    era: "golden",
    icon: "/golden-icons/Blood_Hunters.webp",
  },
  {
    id: 8,
    name: "Iron Reapers",
    src: "/golden-units/ir_rea_pre.png",
    leadership: 300,
    masteryPoints: false,
    value: 9,
    era: "golden",
    icon: "/golden-icons/Iron_Reapers.webp",
  },
  {
    id: 9,
    name: "Kheshigs",
    src: "/golden-units/kheshigs.png",
    leadership: 300,
    masteryPoints: false,
    value: 1,
    era: "golden",
    icon: "/golden-icons/Keshigs.webp",
  },
  {
    id: 10,
    name: "Liaos Rangers",
    src: "/golden-units/liaos_rangers_thumb.png",
    leadership: 315,
    masteryPoints: false,
    value: 6,
    era: "golden",
    icon: "/golden-icons/Liaos_rangers.webp",
  },
  {
    id: 11,
    name: "Modao Battalion",
    src: "/golden-units/modao_battalion_thumb.png",
    leadership: 310,
    masteryPoints: false,
    value: 10,
    era: "golden",
    icon: "/golden-icons/Dynastic_Guards.webp",
  },
  {
    id: 12,
    name: "Monastic Knights",
    src: "/golden-units/mona_kni.png",
    leadership: 295,
    masteryPoints: false,
    value: 6,
    era: "golden",
    icon: "/golden-icons/Elite_Monastic_Knights.webp",
  },
  {
    id: 13,
    name: "Orochi Samurai",
    src: "/golden-units/orochi_samurai_thumb.png",
    leadership: 295,
    masteryPoints: false,
    value: 7,
    era: "golden",
    icon: "/golden-icons/Orochi_Samurais.webp",
  },
  {
    id: 14,
    name: "Pavise Crossbowmen",
    src: "/golden-units/pavi_cros.png",
    leadership: 280,
    masteryPoints: false,
    value: 2,
    era: "golden",
    icon: "/golden-icons/Pavise_Crossbowman.webp",
  },
  {
    id: 15,
    name: "Rattan Rangers",
    src: "/golden-units/ratt_ran_pre.png",
    leadership: 295,
    masteryPoints: false,
    value: 1,
    era: "golden",
    icon: "/golden-icons/Rattan_Rangers.webp",
  },
  {
    id: 16,
    name: "Shenji Grenadiers",
    src: "/golden-units/shenji_grenadiers_thumb.png",
    leadership: 315,
    masteryPoints: false,
    value: 7,
    era: "golden",
    icon: "/golden-icons/Shenji_Grenadiers.webp",
  },
  {
    id: 17,
    name: "Shieldmaidens",
    src: "/golden-units/shieldmaidens_thumb.png",
    leadership: 280,
    masteryPoints: false,
    value: 7,
    era: "golden",
    icon: "/golden-icons/Shieldmaidens.webp",
  },
  {
    id: 18,
    name: "Silahdars",
    src: "/golden-units/sihl_thumb.png",
    leadership: 300,
    masteryPoints: false,
    value: 9,
    era: "golden",
    icon: "/golden-icons/Silahdars.webp",
  },
  {
    id: 19,
    name: "Tercio Arquebusiers",
    src: "/golden-units/tercio.png",
    leadership: 280,
    masteryPoints: false,
    value: 4,
    era: "golden",
    icon: "/golden-icons/Tercio_Arquebusiers.webp",
  },
  {
    id: 20,
    name: "Varangian Guards",
    src: "/golden-units/varangian_guards_thumb.png",
    leadership: 290,
    masteryPoints: false,
    value: 2,
    era: "golden",
    icon: "/golden-icons/Kings_Guards.webp",
  },
  {
    id: 21,
    name: "Winged Hussars",
    src: "/golden-units/win_hus_pre.png",
    leadership: 305,
    masteryPoints: false,
    value: 9,
    era: "golden",
    icon: "/golden-icons/Elite_Winged_Hussars.webp",
  },
  {
    id: 22,
    name: "Yanyuedao Cavalry",
    src: "/golden-units/yanyuedao_cav_thumb.png",
    leadership: 320,
    masteryPoints: false,
    value: 9,
    era: "golden",
    icon: "/golden-icons/Yanyudea_enforcers.webp",
  },
  {
    id: 23,
    name: "Zweihanders",
    src: "/golden-units/zweihanders_thumb.png",
    leadership: 310,
    masteryPoints: false,
    value: 8,
    era: "golden",
    icon: "/golden-icons/Bloodied_Zweihanders.webp",
  },
  {
    id: 24,
    name: "Retiarii",
    src: "/golden-units/retiarii_thumb.png",
    leadership: 305,
    masteryPoints: false,
    value: 1,
    era: "golden",
    icon: "/golden-icons/Retiarii.webp",
  },
  {
    id: 25,
    name: "Queens Knights",
    src: "/golden-units/QK.png",
    leadership: 295,
    masteryPoints: false,
    value: 10,
    era: "golden",
    icon: "/golden-icons/Queens_Paladins.webp",
  },
  {
    id: 26,
    name: "Xuanjia Heavy Cavalr",
    src: "/golden-units/Xuandzia.png",
    leadership: 295,
    masteryPoints: false,
    value: 10,
    era: "golden",
    icon: "/golden-icons/Star_Banner_Cavalry.png",
  },
  {
    id: 27,
    name: "Sunward Phalanx",
    src: "/golden-units/Soneczna_falanga.webp",
    leadership: 290,
    masteryPoints: false,
    value: 9,
    era: "golden",
    icon: "/golden-icons/Soneczna_falanga_icon.webp",
  },
  {
    id: 28,
    name: "Lionroar Crew",
    src: "/golden-units/armaty.png",
    leadership: 310,
    masteryPoints: false,
    value: 9,
    era: "golden",
    icon: "/golden-icons/New_gold_unit.webp",
  },
];
