export const goldenUnits = [
  {
    id: 1,
    name: "Siphonarioi",
    src: "/golden-units/barc-narf-gua-thumb.png",
    leadership: 300,
    masteryPoints: false,
    value: 10,
    era: "golden",
  },
  {
    id: 2,
    name: "Cataphract Lancers",
    src: "/golden-units/cata_lan_pre.png",
    leadership: 305,
    masteryPoints: false,
    value: 5,
    era: "golden",
  },
  {
    id: 3,
    name: "Chevaliers",
    src: "/golden-units/chevaliers_thumb.png",
    leadership: 340,
    masteryPoints: false,
    value: 6,
    era: "golden",
  },
  {
    id: 4,
    name: "Falconetti Gunners",
    src: "/golden-units/falco_gun.png",
    leadership: 300,
    masteryPoints: false,
    value: 10,
    era: "golden",
  },
  {
    id: 5,
    name: "Fire Lancers",
    src: "/golden-units/fire_lan_pre.png",
    leadership: 285,
    masteryPoints: false,
    value: 4,
    era: "golden",
  },
  {
    id: 6,
    name: "Hashashins",
    src: "/golden-units/hashashins_thumb.png",
    leadership: 295,
    masteryPoints: false,
    value: 2,
    era: "golden",
  },
  {
    id: 7,
    name: "Houndsmen",
    src: "/golden-units/houndsmen_thumb.png",
    leadership: 310,
    masteryPoints: false,
    value: 3,
    era: "golden",
  },
  {
    id: 8,
    name: "Iron Reapers",
    src: "/golden-units/ir_rea_pre.png",
    leadership: 300,
    masteryPoints: false,
    value: 7,
    era: "golden",
  },
  {
    id: 9,
    name: "Kheshigs",
    src: "/golden-units/kheshigs.png",
    leadership: 300,
    masteryPoints: false,
    value: 1,
    era: "golden",
  },
  {
    id: 10,
    name: "Liaos Rangers",
    src: "/golden-units/liaos_rangers_thumb.png",
    leadership: 315,
    masteryPoints: false,
    value: 6,
    era: "golden",
  },
  {
    id: 11,
    name: "Modao Battalion",
    src: "/golden-units/modao_battalion_thumb.png",
    leadership: 310,
    masteryPoints: false,
    value: 10,
    era: "golden",
  },
  {
    id: 12,
    name: "Monastic Knights",
    src: "/golden-units/mona_kni.png",
    leadership: 295,
    masteryPoints: false,
    value: 6,
    era: "golden",
  },
  {
    id: 13,
    name: "Orochi Samurai",
    src: "/golden-units/orochi_samurai_thumb.png",
    leadership: 295,
    masteryPoints: false,
    value: 8,
    era: "golden",
  },
  {
    id: 14,
    name: "Pavise Crossbowmen",
    src: "/golden-units/pavi_cros.png",
    leadership: 280,
    masteryPoints: false,
    value: 2,
    era: "golden",
  },
  {
    id: 15,
    name: "Rattan Rangers",
    src: "/golden-units/ratt_ran_pre.png",
    leadership: 295,
    masteryPoints: false,
    value: 1,
    era: "golden",
  },
  {
    id: 16,
    name: "Shenji Grenadiers",
    src: "/golden-units/shenji_grenadiers_thumb.png",
    leadership: 315,
    masteryPoints: false,
    value: 7,
    era: "golden",
  },
  {
    id: 17,
    name: "Shieldmaidens",
    src: "/golden-units/shieldmaidens_thumb.png",
    leadership: 280,
    masteryPoints: false,
    value: 7,
    era: "golden",
  },
  {
    id: 18,
    name: "Silahdars",
    src: "/golden-units/sihl_thumb.png",
    leadership: 300,
    masteryPoints: false,
    value: 4,
    era: "golden",
  },
  {
    id: 19,
    name: "Tercio Arquebusiers",
    src: "/golden-units/tercio.png",
    leadership: 280,
    masteryPoints: false,
    value: 4,
    era: "golden",
  },
  {
    id: 20,
    name: "Varangian Guards",
    src: "/golden-units/varangian_guards_thumb.png",
    leadership: 290,
    masteryPoints: false,
    value: 2,
    era: "golden",
  },
  {
    id: 21,
    name: "Winged Hussars",
    src: "/golden-units/win_hus_pre.png",
    leadership: 305,
    masteryPoints: false,
    value: 9,
    era: "golden",
  },
  {
    id: 22,
    name: "Yanyuedao Cavalry",
    src: "/golden-units/yanyuedao_cav_thumb.png",
    leadership: 320,
    masteryPoints: false,
    value: 9,
    era: "golden",
  },
  {
    id: 23,
    name: "Zweihanders",
    src: "/golden-units/zweihanders_thumb.png",
    leadership: 310,
    masteryPoints: false,
    value: 8,
    era: "golden",
  },
  {
    id: 24,
    name: "Retiarii",
    src: "/golden-units/retiarii_thumb.png",
    leadership: 305,
    masteryPoints: false,
    value: 1,
    era: "golden",
  },
  {
    id: 25,
    name: "Queens Knights",
    src: "/golden-units/QK.png",
    leadership: 295,
    masteryPoints: false,
    value: 10,
    era: "golden",
  },
  {
    id: 26,
    name: "Xuanjia Heavy Cavalr",
    src: "/golden-units/Xuandzia.png",
    leadership: 295,
    masteryPoints: false,
    value: 10,
    era: "golden",
  },
];
