export const heroicUnits = [
  {
    id: 1,
    name: "Armiger Lancers",
    src: "/heroic-units/armiger_lancers_thumb.png",
    leadership: 235,
    masteryPoints: false,
    value: 5,
    era: "heroic",
    icon: "/heroic-icons/Armiger_Lancers.webp",
  },
  {
    id: 2,
    name: "Axe Riders",
    src: "/heroic-units/axe_raiders_thumb.png",
    leadership: 0,
    masteryPoints: false,
    value: 2,
    era: "heroic",
    icon: "/heroic-icons/Axe_Raiders.webp",
  },
  {
    id: 3,
    name: "Azaps",
    src: "/heroic-units/azap_thumb.png",
    leadership: 0,
    masteryPoints: false,
    value: 1,
    era: "heroic",
    icon: "/heroic-icons/Azaps.webp",
  },
  {
    id: 4,
    name: "Banner Guards",
    src: "/heroic-units/banner_guards_thumb.png",
    leadership: 225,
    masteryPoints: false,
    value: 2,
    era: "heroic",
    icon: "/heroic-icons/Oriflamme_Guards.webp",
  },
  {
    id: 5,
    name: "Berserkers",
    src: "/heroic-units/berserker_thumb.png",
    leadership: 245,
    masteryPoints: false,
    value: 3,
    era: "heroic",
    icon: "/heroic-icons/Berserkers.webp",
  },
  {
    id: 6,
    name: "Camel Lancers",
    src: "/heroic-units/camel_lancers_thumb.png",
    leadership: 235,
    masteryPoints: false,
    value: 7,
    era: "heroic",
    icon: "/heroic-icons/Camel_Lancers.webp",
  },
  {
    id: 7,
    name: "Claymores",
    src: "/heroic-units/claymores_thumb.png",
    leadership: 235,
    masteryPoints: false,
    value: 2,
    era: "heroic",
    icon: "/heroic-icons/Eastray_Swordsmen.webp",
  },
  {
    id: 8,
    name: "Crescent Monks",
    src: "/heroic-units/crescent_monks_thumb.png",
    leadership: 250,
    masteryPoints: false,
    value: 4,
    era: "heroic",
    icon: "/heroic-icons/Brawling_Brethren.webp",
  },
  {
    id: 9,
    name: "Dagger Axe Lancers",
    src: "/heroic-units/dag_axe_lan_pre.png",
    leadership: 245,
    masteryPoints: false,
    value: 7,
    era: "heroic",
    icon: "/heroic-icons/Dagger-Axe_Lancers.webp",
  },
  {
    id: 10,
    name: "Fortebraccio Pikemen",
    src: "/heroic-units/forte_pike.png",
    leadership: 235,
    masteryPoints: false,
    value: 8,
    era: "heroic",
    icon: "/heroic-icons/Fortebraccio.webp",
  },
  {
    id: 11,
    name: "Greyhair Garrison",
    src: "/heroic-units/greyhair_garrison_thumb.png",
    leadership: 200,
    masteryPoints: false,
    value: 5,
    era: "heroic",
    icon: "/heroic-icons/Linwu_Veterans.webp",
  },
  {
    id: 12,
    name: "Halberdier Sergeants",
    src: "/heroic-units/halb_serg_pre.png",
    leadership: 230,
    masteryPoints: true,
    value: 7,
    era: "heroic",
    icon: "/heroic-icons/Imperial_Sergeants.webp",
  },
  {
    id: 13,
    name: "Huskarls",
    src: "/heroic-units/huskarl_thumb.png",
    leadership: 230,
    masteryPoints: false,
    value: 3,
    era: "heroic",
    icon: "/heroic-icons/Vargrs_Fangs.webp",
  },
  {
    id: 14,
    name: "Imperial Archers",
    src: "/heroic-units/imp_arc_pre.png",
    leadership: 235,
    masteryPoints: true,
    value: 6,
    era: "heroic",
    icon: "/heroic-icons/Imperial_Archers.webp",
  },
  {
    id: 15,
    name: "Imperial Arquebusiers",
    src: "/heroic-units/imp_arq_pre.png",
    leadership: 245,
    masteryPoints: true,
    value: 7,
    era: "heroic",
    icon: "/heroic-icons/Imperial_Arquebusiers.webp",
  },
  {
    id: 16,
    name: "Imperial Javelineers",
    src: "/heroic-units/imp_jav_pre.png",
    leadership: 240,
    masteryPoints: true,
    value: 4,
    era: "heroic",
    icon: "/heroic-icons/Imperial_Javelineers.webp",
  },
  {
    id: 17,
    name: "Imperial Pike Guards",
    src: "/heroic-units/imp_pk_pre.png",
    leadership: 240,
    masteryPoints: true,
    value: 10,
    era: "heroic",
    icon: "/heroic-icons/Imperial_Pikemen.webp",
  },
  {
    id: 18,
    name: "Imperial Spear Guards",
    src: "/heroic-units/imp_spea_guar_pre.png",
    leadership: 240,
    masteryPoints: true,
    value: 10,
    era: "heroic",
    icon: "/heroic-icons/Imperial_Spearmen.webp",
  },
  {
    id: 19,
    name: "Javelin Sergeants",
    src: "/heroic-units/jav_serg_pre.png",
    leadership: 230,
    masteryPoints: true,
    value: 5,
    era: "heroic",
    icon: "/heroic-icons/Javelin_Sergeants.webp",
  },
  {
    id: 20,
    name: "Khevtuul Cavalry",
    src: "/heroic-units/khev_cav.png",
    leadership: 215,
    masteryPoints: false,
    value: 1,
    era: "heroic",
    icon: "/heroic-icons/Kebultoletolelelelelleowie.webp",
  },
  {
    id: 21,
    name: "Kriegsrat Fusiliers",
    src: "/heroic-units/krieg_fus_post.png",
    leadership: 245,
    masteryPoints: true,
    value: 6,
    era: "heroic",
    icon: "/heroic-icons/Kriegsrat_Fusiliers.webp",
  },
  {
    id: 22,
    name: "Kriegsbruders",
    src: "/heroic-units/krieg.png",
    leadership: 230,
    masteryPoints: false,
    value: 8,
    era: "heroic",
    icon: "/heroic-icons/Holy_Kriegsbruders.webp",
  },
  {
    id: 23,
    name: "Men-at-Arms",
    src: "/heroic-units/men_at_arms_pre.png",
    leadership: 215,
    masteryPoints: true,
    value: 9,
    era: "heroic",
    icon: "/heroic-icons/Men-At-Arms.webp",
  },
  {
    id: 24,
    name: "Myrmillones",
    src: "/heroic-units/myrmillones_thumb.png",
    leadership: 245,
    masteryPoints: false,
    value: 6,
    era: "heroic",
    icon: "/heroic-icons/Secutores.webp",
  },
  {
    id: 25,
    name: "Onna-musha",
    src: "/heroic-units/onna_musha_thumb.png",
    leadership: 235,
    masteryPoints: false,
    value: 7,
    era: "heroic",
    icon: "/heroic-icons/Onna_Musha.webp",
  },
  {
    id: 26,
    name: "Palace Guards",
    src: "/heroic-units/pala_guar_pre.png",
    leadership: 230,
    masteryPoints: true,
    value: 7,
    era: "heroic",
    icon: "/heroic-icons/Palace_Guards.webp",
  },
  {
    id: 27,
    name: "Prefecture Heavy Cavalry",
    src: "/heroic-units/pre_hea_cav_pre.png",
    leadership: 225,
    masteryPoints: true,
    value: 7,
    era: "heroic",
    icon: "/heroic-icons/Prefecture_Heavy_Cavalry.webp",
  },
  {
    id: 28,
    name: "Sipahis",
    src: "/heroic-units/sipahi_thumb.png",
    leadership: 215,
    masteryPoints: false,
    value: 1,
    era: "heroic",
    icon: "/heroic-icons/Tuptajace_Konie.webp",
  },
  {
    id: 29,
    name: "Spear Sergeants",
    src: "/heroic-units/spe_sarg_pre.png",
    leadership: 215,
    masteryPoints: true,
    value: 4,
    era: "heroic",
    icon: "/heroic-icons/Spear_Sergeants.webp",
  },
  {
    id: 30,
    name: "Symmachean Paladins",
    src: "/heroic-units/symm_pal_thumb.png",
    leadership: 235,
    masteryPoints: false,
    value: 3,
    era: "heroic",
    icon: "/heroic-icons/Synmachean_Paladins.webp",
  },
  {
    id: 31,
    name: "Symmachean Stalwarts",
    src: "/heroic-units/symm_stal_thumb.png",
    leadership: 240,
    masteryPoints: false,
    value: 3,
    era: "heroic",
    icon: "/heroic-icons/Synmachean_Stalwarts.webp",
  },
  {
    id: 32,
    name: "Tseregs",
    src: "/heroic-units/Tseregi.png",
    leadership: 225,
    masteryPoints: false,
    value: 2,
    era: "heroic",
    icon: "/heroic-icons/tseregs.webp",
  },
  {
    id: 33,
    name: "Vassal Longbowmen",
    src: "/heroic-units/vas_long_pre.png",
    leadership: 245,
    masteryPoints: false,
    value: 5,
    era: "heroic",
    icon: "/heroic-icons/Longbowmen.webp",
  },
  {
    id: 34,
    name: "Yeomen",
    src: "/heroic-units/yeom_pre.png",
    leadership: 225,
    masteryPoints: true,
    value: 7,
    era: "heroic",
    icon: "/heroic-icons/Yeomen.webp",
  },
  {
    id: 35,
    name: "Aschigaru Muskets",
    src: "/heroic-units/Aschigaru.png",
    leadership: 205,
    masteryPoints: false,
    value: 3,
    era: "heroic",
    icon: "/heroic-icons/none",
  },
  {
    id: 36,
    name: "WuWei",
    src: "/heroic-units/wuwej.png",
    leadership: 225,
    masteryPoints: false,
    value: 9,
    era: "heroic",
    icon: "/heroic-icons/Mansion_Guards.webp",
  },
  {
    id: 37,
    name: "Percival Guardsmen",
    src: "/heroic-units/persiwal.png",
    leadership: 225,
    masteryPoints: false,
    value: 4,
    era: "heroic",
    icon: "/heroic-icons/Camelots_Garrison.webp",
  },
];
