const kits = [
  { image: "logo.png", unit: "Lionroar Crew" },
  { image: "logo.png", unit: "Spartan Chosen" },
  { image: "logo.png", unit: "Queens Knights" },
  { image: "logo.png", unit: "Sunward Phalanx" },
  { image: "logo.png", unit: "Xuanjia Heavy Cavalry" },
  { image: "rouncey.png", unit: "Xuanjia Heavy Cavalry" },
  { image: "chevaliers_kit_thumb.png", unit: "Chevaliers" },
  { image: "barb.png", unit: "Chevaliers" },
  { image: "shenji_kit_thumb.png", unit: "Shenji Grenadiers" },
  { image: "falco_kit_thumb.png", unit: "Falconetti Gunners" },
  { image: "fire_lance_kit.png", unit: "Fire Lancers" },
  { image: "rouncey.png", unit: "Fire Lancers" },
  { image: "fire_lance_kit.png", unit: "Liaos Rangers" },
  { image: "rouncey.png", unit: "Liaos Rangers" },
  { image: "hashashins_kit_thumb.png", unit: "Hashashins" },
  { image: "heavy_lance_kit.png", unit: "Monastic Knights" },
  { image: "barb.png", unit: "Monastic Knights" },
  { image: "heavy_lance_kit.png", unit: "Cataphract Lancers" },
  { image: "barb.png", unit: "Cataphract Lancers" },
  { image: "houndsmen_kit_thumb.png", unit: "Houndsmen" },
  { image: "iron_reaper_kit.png", unit: "Iron Reapers" },
  { image: "keshig_kit_thumb.png", unit: "Kheshigs" },
  { image: "rouncey.png", unit: "Kheshigs" },
  { image: "modao_battalion_kit_thumb.png", unit: "Modao Battalion" },
  { image: "musket_kit_b.png", unit: "Tercio Arquebusiers" },
  { image: "orochi_samurais_kit_thumb.png", unit: "Orochi Samurai" },
  { image: "crossbow_kit.png", unit: "Rattan Rangers" },
  { image: "rouncey.png", unit: "Rattan Rangers" },
  { image: "pavise_kit_thumb.png", unit: "Pavise Crossbowmen" },
  { image: "retiarius_kit_thumb.png", unit: "Retiarii" },
  { image: "musket_kit_b.png", unit: "Tercio Arquebusiers" },
  { image: "shieldmaidens_kit_thumb.png", unit: "Shieldmaidens" },
  { image: "sihl_kit_thumb.png", unit: "Silahdars" },
  { image: "sipho_kit.png", unit: "Siphonarioi" },
  { image: "varangian_guardsman_kit_thumb.png", unit: "Varangian Guards" },
  { image: "wing_hus_kit.png", unit: "Winged Hussars" },
  { image: "barb.png", unit: "Winged Hussars" },
  { image: "yanyuedao_cavalrymans_kit_thumb.png", unit: "Yanyuedao Cavalry" },
  { image: "rouncey.png", unit: "Yanyuedao Cavalry" },
  { image: "zweihander_kit_thumb.png", unit: "Zweihanders" },
  { image: "medium_lance_kit.png", unit: "Armiger Lancers" },
  { image: "barb.png", unit: "Armiger Lancers" },
  { image: "axe_raid_kit_thumb.png", unit: "Axe Raiders" },
  { image: "azap_kit_thumb.png", unit: "Azaps" },
  { image: "banner_guards_kit_thumb.png", unit: "Banner Guards" },
  { image: "berserkers_kit_thumb.png", unit: "Berserkers" },
  { image: "camel_lancers_kit_thumb.png", unit: "Camel Lancers" },
  { image: "camel.png", unit: "Camel Lancers" },
  { image: "claymores_kit_thumb.png", unit: "Claymores" },
  { image: "crescent_monks_kit_thumb.png", unit: "Crescent Monks" },
  { image: "dagger_axe_kit.png", unit: "Dagger Axe Lancers" },
  { image: "rouncey.png", unit: "Dagger Axe Lancers" },
  { image: "pike_kit.png", unit: "Fortebraccio Pikemen" },
  { image: "greyhair_garrison_kit_thumb.png", unit: "Greyhair Garrison" },
  { image: "halb_kit.png", unit: "Halberdier Sergeants" },
  { image: "huskarls_kit_thumb.png", unit: "Huskarls" },
  { image: "archer_bow_a.png", unit: "Imperial Archers" },
  { image: "musket_kit_a.png", unit: "Imperial Arquebusiers" },
  { image: "east_jav_kit.png", unit: "Imperial Javelineers" },
  { image: "pike_kit.png", unit: "Imperial Pike Guards" },
  { image: "large_shield_kit.png", unit: "Imperial Spear Guards" },
  { image: "west_jav_kit.png", unit: "Javelin Sergeants" },
  { image: "khev_kit_thumb.png", unit: "Khevtuul Cavalry" },
  { image: "rouncey.png", unit: "Khevtuul Cavalry" },
  { image: "musket_kit_c.png", unit: "Kriegsrat Fusiliers" },
  { image: "kriegsbruders_kit_thumb.png", unit: "Kriegsbruders" },
  { image: "chiv_kit.png", unit: "Men-at-Arms" },
  { image: "myrmillos_kit_thumb.png", unit: "Myrmillones" },
  { image: "onna-mushas_kit_thumb.png", unit: "Onna-musha" },
  { image: "sword_shield_b.png", unit: "Palace Guards" },
  { image: "mounted_sword_kit.png", unit: "Prefecture Heavy Cavalry" },
  { image: "rouncey.png", unit: "Prefecture Heavy Cavalry" },
  { image: "sipahi_kit_thumb.png", unit: "Sipahis" },
  { image: "barb.png", unit: "Sipahis" },
  { image: "chiv_tower_shield.png", unit: "Spear Sergeants" },
  { image: "logo.png", unit: "Symmachean Paladins" },
  { image: "logo.png", unit: "Symmachean Stalwarts" },
  { image: "tsereg_kit_thumb.png", unit: "Tseregs" },
  { image: "archer_bow_a.png", unit: "Vassal Longbowmen" },
  { image: "medium_lance_kit.png", unit: "Yeomen" },
  { image: "logo.png", unit: "Aschigaru Muskets" },
  { image: "logo.png", unit: "WuWei" },
  { image: "logo.png", unit: "Percival Guardsmen" },
  { image: "logo.png", unit: "Companion Cavalry" },
  { image: "logo.png", unit: "Swinefeathers" },
  { image: "logo.png", unit: "Laconic Javelins" },
  { image: "alchemists_kit_thumb.png", unit: "Alchemists" },
  { image: "bagpipers_kit_thumb.png", unit: "Bagpipers" },
  { image: "zyk_kit_thumb.png", unit: "Zykalian Militia" },
  { image: "logo.png", unit: "Condottieri Guards" },
  { image: "cudgel_monk_kit_thumb.png", unit: "Cudgel Monks" },
  { image: "crossbow_kit.png", unit: "Demesne Arbalists" },
  { image: "musket_kit_a.png", unit: "Demesne Arquebusiers" },
  { image: "dimachaerus_kit_thumb.png", unit: "Dimachaeri" },
  { image: "halb_kit.png", unit: "Halberdiers" },
  { image: "archer_kit_c.png", unit: "Incendiary Archers" },
  { image: "large_shield_kit.png", unit: "Ironcap Spearmen" },
  { image: "jangjus_kit_thumb.png", unit: "Jangjus" },
  { image: "janis_kit_thumb.png", unit: "Janissaries" },
  { image: "nomad_bow_kit_thumb.png", unit: "Khorchins" },
  { image: "courser.png", unit: "Khorchins" },
  { image: "halb_kit.png", unit: "Landsknechts" },
  { image: "nomad_bow_kit_thumb.png", unit: "Namkhan Archers" },
  { image: "outriders_kit_thumb.png", unit: "Outriders" },
  { image: "courser.png", unit: "Outriders" },
  { image: "archer_kit_c.png", unit: "Prefecture Archers" },
  { image: "sword_shield_b.png", unit: "Prefecture Guards" },
  { image: "pike_kit.png", unit: "Prefecture Pikemen" },
  { image: "logo.png", unit: "Feathered Crossbowmen" },
  { image: "crossbow_kit.png", unit: "Rattan Marksmen" },
  { image: "archer_kit_c.png", unit: "Rattan Vipers" },
  { image: "ronins_kit_thumb.png", unit: "Ronin" },
  { image: "schutzdieners_kit_thumb.png", unit: "Schutzdieners" },
  { image: "son_of_fen_kit_thumb.png", unit: "Sons of Fenrir" },
  { image: "chiv_kit.png", unit: "Squires" },
  { image: "archer_kit_c.png", unit: "Vanguard Archers" },
  { image: "wuxing_pikemen_kit_thumb.png", unit: "Wuxing Pikemen" },
  { image: "logo.png", unit: "Caradocs Cavalry" },
  { image: "courser.png", unit: "Caradocs Cavalry" },
  { image: "logo.png", unit: "Psiloi Slingers" },
  { image: "logo.png", unit: "Reitar Pistoleers" },
  { image: "courser.png", unit: "Reitar Pistoleers" },
  { image: "courser.png", unit: "Selemchid Cavalry" },
  { image: "logo.png", unit: "Helot Auxiliaries" },
  { image: "medium_lance_kit.png", unit: "Coutiliers" },
  { image: "jennet.png", unit: "Coutiliers" },
  { image: "archer_kit_b.png", unit: "Demesne Archers" },
  { image: "crossbow_kit.png", unit: "Demesne Crossbowmen" },
  { image: "west_jav_kit.png", unit: "Demesne Javelineers" },
  { image: "chiv_tower_shield.png", unit: "Demesne Spearmen" },
  { image: "archer_kit_b.png", unit: "Ironcap Archers" },
  { image: "musket_kit_a.png", unit: "Ironcap Arquebusiers" },
  { image: "sword_shield_a.png", unit: "Ironcap Swordsmen" },
  { image: "east_jav_kit.png", unit: "Javelin Militia" },
  { image: "pike_kit.png", unit: "Pike Militia" },
  { image: "pike_kit.png", unit: "Rattan Pikemen" },
  { image: "sword_shield_a.png", unit: "Rattan Roundshields" },
  { image: "mounted_sword_kit.png", unit: "Ironcap Scout Cavalry" },
  { image: "archer_kit_a.png", unit: "Archer Militia" },
  { image: "musket_kit_a.png", unit: "Levy Bowmen" },
  { image: "spear_mil_kit.png", unit: "Spear Militia" },
  { image: "sword_shield_a.png", unit: "Sword Militia" },
  { image: "archer_kit_b.png", unit: "Ironcap Bowriders" },
  { image: "jennet.png", unit: "Ironcap Bowriders" },
];

export default kits;
