const kits = [
  { image: "chevaliers_kit_thumb.png", unit: "Chevaliers" },
  { image: "falco_kit_thumb.png", unit: "Falconetti Gunners" },
  { image: "fire_lance_kit.png", unit: "Fire Lancers" },
  { image: "hashashins_kit_thumb.png", unit: "Hashashins" },
  { image: "heavy_lance_kit.png", unit: "Monastic Knights" },
  { image: "heavy_lance_kit.png", unit: "Cataphract Lancers" },
  { image: "houndsmen_kit_thumb.png", unit: "Houndsmen" },
  { image: "iron_reaper_kit.png", unit: "Iron Reapers" },
  { image: "keshig_kit_thumb.png", unit: "Kheshigs" },
  { image: "modao_battalion_kit_thumb.png", unit: "Modao Battalion" },
  { image: "musket_kit_b.png", unit: "Tercio Arquebusiers" },
  { image: "orochi_samurais_kit_thumb.png", unit: "Orochi Samurai" },
  { image: "pavise_kit_thumb.png", unit: "Pavise Crossbowmen" },
  { image: "retiarius_kit_thumb.png", unit: "Retiarii" },
  { image: "shenji_kit_thumb.png", unit: "Tercio Arquebusiers" },
  { image: "shieldmaidens_kit_thumb.png", unit: "Shieldmaidens" },
  { image: "sihl_kit_thumb.png", unit: "Silahdars" },
  { image: "sipho_kit.png", unit: "Siphonarioi" },
  { image: "varangian_guardsman_kit_thumb.png", unit: "Varangian Guards" },
  { image: "wing_hus_kit.png", unit: "Winged Hussars" },
  { image: "yanyuedao_cavalrymans_kit_thumb.png", unit: "Yanyuedao Cavalry" },
  { image: "zweihander_kit_thumb.png", unit: "Zweihanders" },
];

export default kits;
