export const lowUnits = [
  {
    id: 1,
    name: "Alchemists",
    src: "/low-tiers-units/alchemists_thumb.png",
    leadership: 60,
    masteryPoints: false,
    value: 5,
    era: "blue",
    icon: "/low-tiers-icons/Alchemists.webp",
  },
  {
    id: 2,
    name: "Archer Militia",
    src: "/low-tiers-units/arc_mil_pre.png",
    masteryPoints: false,
    leadership: 0,
    value: 6,
    era: "grey",
    icon: "/unit.jpg",
  },
  {
    id: 3,
    name: "Bagpipers",
    src: "/low-tiers-units/bagpipers_thumb.png",
    leadership: 90,
    masteryPoints: false,
    value: 2,
    era: "blue",
    icon: "/low-tiers-icons/Bagpipers.webp",
  },
  {
    id: 4,
    name: "Zykalian Militia",
    src: "/low-tiers-units/barc-wild-thumb.png",
    leadership: 175,
    masteryPoints: false,
    value: 10,
    era: "blue",
    icon: "/low-tiers-icons/Zykalian_Militia.webp",
  },
  {
    id: 5,
    name: "Black Dragon Archers",
    src: "/low-tiers-units/bla_drag_arc.png",
    leadership: 60,
    masteryPoints: false,
    value: 5,
    era: "green",
    icon: "/unit.jpg",
  },
  {
    id: 6,
    name: "Black Dragon Javelineers",
    src: "/low-tiers-units/bla_drag_jav.png",
    leadership: 80,
    masteryPoints: false,
    value: 3,
    era: "blue",
    icon: "/unit.jpg",
  },
  {
    id: 7,
    name: "Black Dragon Pikemen",
    src: "/low-tiers-units/bla_drag_pike.png",
    leadership: 80,
    masteryPoints: false,
    value: 3,
    era: "blue",
    icon: "/unit.jpg",
  },
  {
    id: 8,
    name: "Black Dragon Spearmen",
    src: "/low-tiers-units/bla_drag_spear.png",
    leadership: 80,
    masteryPoints: false,
    value: 3,
    era: "blue",
    icon: "/unit.jpg",
  },
  {
    id: 9,
    name: "Condottieri Guards",
    src: "/low-tiers-units/condo_gua.png",
    leadership: 160,
    masteryPoints: false,
    value: 7,
    era: "blue",
    icon: "/low-tiers-icons/Condottieri_Guards.webp",
  },
  {
    id: 10,
    name: "Coutiliers",
    src: "/low-tiers-units/couts_pre.png",
    leadership: 115,
    masteryPoints: false,
    value: 8,
    era: "green",
    icon: "/low-tiers-icons/Coutiliers.webp",
  },
  {
    id: 11,
    name: "Cudgel Monks",
    src: "/low-tiers-units/cudgel_monks_thumb.png",
    leadership: 145,
    masteryPoints: false,
    value: 4,
    era: "blue",
    icon: "/low-tiers-icons/Cudgel_Monks.webp",
  },
  {
    id: 12,
    name: "Demesne Arbalists",
    src: "/low-tiers-units/dem_arb_pre.png",
    leadership: 160,
    masteryPoints: false,
    value: 3,
    era: "blue",
    icon: "/low-tiers-icons/Arbalists.webp",
  },
  {
    id: 13,
    name: "Demesne Archers",
    src: "/low-tiers-units/dem_arc_pre.png",
    leadership: 90,
    masteryPoints: false,
    value: 2,
    era: "green",
    icon: "/low-tiers-icons/Demesne_Archers.webp",
  },
  {
    id: 14,
    name: "Demesne Arquebusiers",
    src: "/low-tiers-units/dem_arqu_pre.png",
    leadership: 170,
    masteryPoints: false,
    value: 3,
    era: "blue",
    icon: "/low-tiers-icons/Demesne_Arquebusiers.webp",
  },
  {
    id: 15,
    name: "Demesne Crossbowmen",
    src: "/low-tiers-units/dem_cros.png",
    leadership: 110,
    masteryPoints: false,
    value: 5,
    era: "green",
    icon: "/low-tiers-icons/Demesne_Crossbowmen.webp",
  },
  {
    id: 16,
    name: "Demesne Javelineers",
    src: "/low-tiers-units/dem_jav_pre.png",
    leadership: 105,
    masteryPoints: false,
    value: 2,
    era: "green",
    icon: "/unit.jpg",
  },
  {
    id: 17,
    name: "Demesne Spearmen",
    src: "/low-tiers-units/dem_spe_pre.png",
    leadership: 105,
    masteryPoints: false,
    value: 3,
    era: "green",
    icon: "/low-tiers-icons/Demesne_Spearmen.webp",
  },
  {
    id: 18,
    name: "Dimachaeri",
    src: "/low-tiers-units/dimachaeri_thumb.png",
    leadership: 165,
    masteryPoints: false,
    value: 6,
    era: "blue",
    icon: "/low-tiers-icons/Dimacheri.webp",
  },
  {
    id: 19,
    name: "Halberdiers",
    src: "/low-tiers-units/halb_pre.png",
    leadership: 165,
    masteryPoints: true,
    value: 9,
    era: "blue",
    icon: "/low-tiers-icons/Halberdiers.webp",
  },
  {
    id: 20,
    name: "Incendiary Archers",
    src: "/low-tiers-units/ind_arc_pre.png",
    leadership: 180,
    masteryPoints: false,
    value: 6,
    era: "blue",
    icon: "/low-tiers-icons/Rattan_Vipers.webp",
  },
  {
    id: 21,
    name: "Ironcap Archers",
    src: "/low-tiers-units/iro_arc_pre.png",
    leadership: 110,
    masteryPoints: false,
    value: 2,
    era: "green",
    icon: "/low-tiers-icons/Ironcap_Archers.webp",
  },
  {
    id: 22,
    name: "Ironcap Arquebusiers",
    src: "/low-tiers-units/iro_arqu_pre.png",
    leadership: 120,
    masteryPoints: false,
    value: 2,
    era: "green",
    icon: "/low-tiers-icons/Ironcap_Arquebusiers.webp",
  },
  {
    id: 23,
    name: "Ironcap Bowriders",
    src: "/low-tiers-units/iro_bow_pre.png",
    leadership: 90,
    masteryPoints: true,
    value: 2,
    era: "green",
    icon: "/unit.jpg",
  },
  {
    id: 24,
    name: "Ironcap Scout Cavalry",
    src: "/low-tiers-units/iro_sco_cav_pre.png",
    leadership: 120,
    masteryPoints: true,
    value: 9,
    era: "green",
    icon: "/low-tiers-icons/Ironcap_Scouts.webp",
  },
  {
    id: 25,
    name: "Ironcap Spearmen",
    src: "/low-tiers-units/iro_spear_pre.png",
    leadership: 135,
    masteryPoints: true,
    value: 8,
    era: "blue",
    icon: "/low-tiers-icons/Ironcap_SPearmen.webp",
  },
  {
    id: 26,
    name: "Ironcap Swordsmen",
    src: "/low-tiers-units/iron_swor_pre.png",
    leadership: 100,
    masteryPoints: true,
    value: 6,
    era: "green",
    icon: "/low-tiers-icons/Ironcap_Swordsmen.webp",
  },
  {
    id: 27,
    name: "Jangjus",
    src: "/low-tiers-units/jangjus_thumb.png",
    leadership: 170,
    masteryPoints: false,
    value: 6,
    era: "blue",
    icon: "/low-tiers-icons/Jangjus.webp",
  },
  {
    id: 28,
    name: "Janissaries",
    src: "/low-tiers-units/janissary_thumb.png",
    leadership: 180,
    masteryPoints: false,
    value: 7,
    era: "blue",
    icon: "/low-tiers-icons/Janissaries.webp",
  },
  {
    id: 29,
    name: "Javelin Militia",
    src: "/low-tiers-units/jav_mil_pre.png",
    leadership: 105,
    masteryPoints: true,
    value: 2,
    era: "green",
    icon: "/low-tiers-icons/Javelin_Militia.webp",
  },
  {
    id: 30,
    name: "Khorchins",
    src: "/low-tiers-units/khorchins.png",
    leadership: 140,
    masteryPoints: false,
    value: 1,
    era: "blue",
    icon: "/low-tiers-icons/Khorchins.webp",
  },
  {
    id: 31,
    name: "Landsknechts",
    src: "/low-tiers-units/landsknechts_thumb.png",
    leadership: 165,
    masteryPoints: false,
    value: 7,
    era: "blue",
    icon: "/low-tiers-icons/Landsknechts.webp",
  },
  {
    id: 32,
    name: "Levy Bowmen",
    src: "/low-tiers-units/lev_bow_pre.png",
    leadership: 50,
    masteryPoints: false,
    value: 1,
    era: "grey",
    icon: "/low-tiers-icons/Levy_Bowmen.webp",
  },
  {
    id: 33,
    name: "Mace Sergeants",
    src: "/low-tiers-units/mace_sergeants_thumb.png",
    leadership: 150,
    masteryPoints: true,
    value: 9,
    era: "blue",
    icon: "/low-tiers-icons/Mace_Sergeants.webp",
  },
  {
    id: 34,
    name: "Martellatori",
    src: "/low-tiers-units/martella.png",
    leadership: 30,
    masteryPoints: false,
    value: 10,
    era: "grey",
    icon: "/low-tiers-icons/Martelatori.webp",
  },
  {
    id: 35,
    name: "Namkhan Archers",
    src: "/low-tiers-units/nam_arch.png",
    leadership: 180,
    masteryPoints: false,
    value: 4,
    era: "blue",
    icon: "/low-tiers-icons/Namkhan_Archers.webp",
  },
  {
    id: 36,
    name: "Outriders",
    src: "/low-tiers-units/outriders_thumb.png",
    leadership: 180,
    masteryPoints: false,
    value: 7,
    era: "blue",
    icon: "/low-tiers-icons/Outriders.webp",
  },
  {
    id: 37,
    name: "Pike Militia",
    src: "/low-tiers-units/pk_mil_pre.png",
    leadership: 110,
    masteryPoints: true,
    value: 7,
    era: "green",
    icon: "/low-tiers-icons/Pike_Militia.webp",
  },
  {
    id: 38,
    name: "Prefecture Archers",
    src: "/low-tiers-units/pref_arc_pre.png",
    leadership: 180,
    masteryPoints: false,
    value: 4,
    era: "blue",
    icon: "/low-tiers-icons/Rattan_Vipers.webp",
  },
  {
    id: 39,
    name: "Prefecture Guards",
    src: "/low-tiers-units/pref_guar_pre.png",
    leadership: 170,
    masteryPoints: true,
    value: 10,
    era: "blue",
    icon: "/low-tiers-icons/Prefecture_Guards.webp",
  },
  {
    id: 40,
    name: "Prefecture Pikemen",
    src: "/low-tiers-units/pref_pike_pre.png",
    leadership: 165,
    masteryPoints: true,
    value: 7,
    era: "blue",
    icon: "/low-tiers-icons/Prefecture_Pikemens.webp",
  },
  {
    id: 41,
    name: "Feathered Crossbowmen",
    src: "/low-tiers-units/dragonrise.png",
    leadership: 150,
    masteryPoints: false,
    value: 6,
    era: "blue",
    icon: "/low-tiers-icons/Feathered_Crossbowmen.webp",
  },
  {
    id: 42,
    name: "Rattan Marksmen",
    src: "/low-tiers-units/ratt_mar_pre.png",
    leadership: 175,
    masteryPoints: true,
    value: 8,
    era: "blue",
    icon: "/low-tiers-icons/Rattan_Marksmen.webp",
  },
  {
    id: 43,
    name: "Rattan Pikemen",
    src: "/low-tiers-units/ratt_pik_pre.png",
    leadership: 95,
    masteryPoints: true,
    value: 6,
    era: "green",
    icon: "/low-tiers-icons/Pike_Militia.webp",
  },
  {
    id: 44,
    name: "Rattan Roundshields",
    src: "/low-tiers-units/ratt_rou_pre.png",
    leadership: 115,
    masteryPoints: true,
    value: 3,
    era: "green",
    icon: "/low-tiers-icons/Rattan_Roundshields.webp",
  },
  {
    id: 45,
    name: "Rattan Vipers",
    src: "/low-tiers-units/ratt_vip_pre.png",
    leadership: 155,
    masteryPoints: false,
    value: 2,
    era: "blue",
    icon: "/low-tiers-icons/Rattan_Vipers.webp",
  },
  {
    id: 46,
    name: "Ronin",
    src: "/low-tiers-units/ronin_thumb.png",
    leadership: 145,
    masteryPoints: false,
    value: 4,
    era: "blue",
    icon: "/low-tiers-icons/Ronin.webp",
  },
  {
    id: 47,
    name: "Schutzdieners",
    src: "/low-tiers-units/schutzdieners_thumb.png",
    leadership: 165,
    masteryPoints: false,
    value: 3,
    era: "blue",
    icon: "/low-tiers-icons/Schutzdieners.webp",
  },
  {
    id: 48,
    name: "Sea Stag Deathdealers",
    src: "/low-tiers-units/sea_stag_death.png",
    leadership: 80,
    masteryPoints: false,
    value: 2,
    era: "blue",
    icon: "/unit.jpg",
  },
  {
    id: 49,
    name: "Selemchid Cavalry",
    src: "/low-tiers-units/selem_cav.png",
    leadership: 150,
    masteryPoints: false,
    value: 3,
    era: "blue",
    icon: "/unit.jpg",
  },
  {
    id: 50,
    name: "Serfs",
    src: "/low-tiers-units/serfs_pre.png",
    leadership: 40,
    masteryPoints: false,
    value: 1,
    era: "grey",
    icon: "/low-tiers-icons/Serfs.webp",
  },
  {
    id: 51,
    name: "Sons of Fenrir",
    src: "/low-tiers-units/sons_of_fenrir_thumb.png",
    leadership: 165,
    masteryPoints: false,
    value: 7,
    era: "blue",
    icon: "/low-tiers-icons/Favourite_Sons.webp",
  },
  {
    id: 52,
    name: "Spear Militia",
    src: "/low-tiers-units/spear_mil.png",
    leadership: 80,
    masteryPoints: false,
    value: 2,
    era: "grey",
    icon: "/unit.jpg",
  },
  {
    id: 53,
    name: "Squires",
    src: "/low-tiers-units/squires_pre.png",
    leadership: 155,
    masteryPoints: true,
    value: 5,
    era: "blue",
    icon: "/low-tiers-icons/Squires.webp",
  },
  {
    id: 54,
    name: "Sword Militia",
    src: "/low-tiers-units/sword_mil_post.png",
    leadership: 65,
    masteryPoints: false,
    value: 2,
    era: "grey",
    icon: "/unit.jpg",
  },
  {
    id: 55,
    name: "Tenant Farmers",
    src: "/low-tiers-units/ten_farm_pre.png",
    leadership: 40,
    masteryPoints: false,
    value: 1,
    era: "grey",
    icon: "/unit.jpg",
  },
  {
    id: 56,
    name: "Vanguard Archers",
    src: "/low-tiers-units/van_arc_pre.png",
    leadership: 150,
    masteryPoints: false,
    value: 2,
    era: "blue",
    icon: "/low-tiers-icons/Rattan_Vipers.webp",
  },
  {
    id: 57,
    name: "Village Watchmen",
    src: "/low-tiers-units/vil_watch_pre.png",
    leadership: 30,
    masteryPoints: false,
    value: 1,
    era: "grey",
    icon: "/low-tiers-icons/Village_Watchmen.webp",
  },
  {
    id: 58,
    name: "Woodcutters",
    src: "/low-tiers-units/woo_cut_pre.png",
    leadership: 30,
    masteryPoints: false,
    value: 1,
    era: "grey",
    icon: "/low-tiers-icons/Woodcutters.webp",
  },
  {
    id: 59,
    name: "Wuxing Pikemen",
    src: "/low-tiers-units/wuxing_pike_thumb.png",
    leadership: 155,
    masteryPoints: false,
    value: 7,
    era: "blue",
    icon: "/low-tiers-icons/Wuxing_Pikemen.webp",
  },
  {
    id: 60,
    name: "Naginata Monks",
    src: "/low-tiers-units/mnisi_z_naginantami.png",
    leadership: 125,
    masteryPoints: false,
    value: 7,
    era: "blue",
    icon: "/low-tiers-icons/Naginata_Monks.webp",
  },
  {
    id: 61,
    name: "Caradocs Cavalry",
    src: "/low-tiers-units/karndogi.png",
    leadership: 195,
    masteryPoints: false,
    value: 4,
    era: "blue",
    icon: "/low-tiers-icons/Caradocs_Cavalry.webp",
  },
];
