export const others = [
  {
    era: "other",
    icon: "/others-units/cav.jpg",
    id: 90,
    leadership: 0,
    masteryPoints: false,
    name: "Cavalry",
    src: "",
    value: 10,
  },
  {
    era: "other",
    icon: "/others-units/piki.jpg",
    id: 91,
    leadership: 0,
    masteryPoints: false,
    name: "Anti Cavalry",
    src: "",
    value: 10,
  },
  {
    era: "other",
    icon: "/others-units/zbrojni.jpg",
    id: 92,
    leadership: 0,
    masteryPoints: false,
    name: "Armed Infantry",
    src: "",
    value: 10,
  },
  {
    era: "other",
    icon: "/others-units/special.jpg",
    id: 93,
    leadership: 0,
    masteryPoints: false,
    name: "Special",
    src: "",
    value: 10,
  },
];
